### ISSUE TITLE
meshrender and chamfer files missing?

### ISSUE THREAD

**Issue by bmauchly** [chenhsuanlin/photometric-mesh-optim#2]
The demo code tries to
from meshrender import _meshrender  
but can't find it.  Where does it come from?
chamfer directory is also empty.

**Comment by chenhsuanlin** [comment]
I realized it was missing and updated the repo yesterday. Could you try pulling again? There should be a `_meshrender.so` library file.

**Comment by chenhsuanlin** [comment]
Closing for now, please feel free to reopen for further issues!
