### ISSUE TITLE
Pretrained models can't be downloaded.

### ISSUE THREAD

**Issue by TopGun666** [chenhsuanlin/photometric-mesh-optim#4]
Pretrained models can't be downloaded. 

> --2019-06-29 15:11:40--  (try: 5)  https://cmu.app.box.com/public/static/oryysitkhn2eldgb90qkr3lh7j469sj1.npz
Connecting to cmu.app.box.com (cmu.app.box.com)|59.24.3.173|:443... failed: Connection timed out.
>--2019-06-29 15:13:57--  (try: 6)  https://cmu.app.box.com/public/static/oryysitkhn2eldgb90qkr3lh7j469sj1.npz
Connecting to cmu.app.box.com (cmu.app.box.com)|59.24.3.173|:443... failed: Connection refused.

**Comment by chenhsuanlin** [comment]
The link works on my side. Do you have a firewall blocking you or something like that?

**Comment by TopGun666** [comment]
I tried it in Guangzhou and Xi'an with IPV4, IPV6 even VPN, but none of them work. Could you please upload your Pretrained models on the BaiduYun or OneDrive？Maybe the link doesn't work in China Mainland.

**Comment by TopGun666** [comment]
Thank you. I have solve the problem with VPN.
