### ISSUE TITLE
Add tensorflow (to run tensorboardX visualizations) to requirements.txt

### ISSUE THREAD

**Issue by prachees** [chenhsuanlin/photometric-mesh-optim#6]
It seems like tensorflow is needed in order to visualize the tensorboardX files. The command listed on the README 
"tensorboard --logdir=summary/GROUP --port=6006" does not work otherwise.

**Comment by chenhsuanlin** [comment]
Sorry for getting to this late, this has been fixed. Thanks for reporting the issue!
