### ISSUE TITLE
Pretrained AtlasNet not found

### ISSUE THREAD

**Issue by ivansipiran** [chenhsuanlin/photometric-mesh-optim#8]
Hi,

I am trying to replicate the training. However, I could not find the file "ae_atlasnet_25.pth" in the AtlasNet repository. Please could you give me more information about where to find the pretrained AtlasNet?

Best regards

**Comment by chenhsuanlin** [comment]
It seems that the AtlasNet repo has been greatly refactored. I think the pretrained model probably corresponds to `atlasnet_autoencoder_25_squares/network.pth` in https://github.com/ThibaultGROUEIX/AtlasNet/blob/master/doc/demo.md. Just a bit of renaming in the code and you should be good to go 🙂
